version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees: [KiwiKilian]

  - package-ecosystem: npm
    directories:
      - /2024-ss-mmt-m-frontend-engineering/
      - /2024-ws-mmt-m-guest-lecture-web-engineering/
      - /2025-ss-mmt-m-frontend-engineering/
    schedule:
      interval: weekly
    assignees: [KiwiKilian]
